# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dragonfly-styles}
  s.version = "0.8.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Neill"]
  s.date = %q{2010-11-25}
  s.email = %q{alex@rawnet.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "lib/dragonfly-styles.rb",
    "lib/dragonfly/active_record_extensions/attachment.rb",
    "lib/dragonfly/active_record_extensions/class_methods.rb",
    "lib/dragonfly/app.rb"
  ]
  s.homepage = %q{http://github.com/ajn/dragonfly-styles}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Extends Dragonfly to allow for paperclip-like style definitions.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dragonfly>, [">= 0"])
    else
      s.add_dependency(%q<dragonfly>, [">= 0"])
    end
  else
    s.add_dependency(%q<dragonfly>, [">= 0"])
  end
end

